sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.decorators.cache import cache_page

from sitewomen import settings
from women.sitemaps import PostSitemap, CategorySitemap
from women.views import page_not_found
import women

sitemaps = {
    'posts': PostSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', cache_page(15900)(sitemap), {'sitemaps': sitemaps}, 'django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Известные женщины мира"

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users import views


app_name = "users"

urlpatterns = [path('login/', views.LoginUser.as_view(), name='login'),
               path('logout/', LogoutView.as_view(), name='logout'),
               path('register/', views.RegisterUser.as_view(), name='register'),
               path('profile/', views.ProfileUser.as_view(), name='profile'),

               path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
               path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
                    name='password_change_done'),

               path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                                 email_template_name='users/password_reset_email.html',
                                                                 success_url=reverse_lazy('users:password_reset_done')
                                                                 ),
                    name='password_reset'),
               path('password_reset_done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
                    name='password_reset_done'),
               path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                                                success_url=reverse_lazy('users:password_reset_complete')),
                    name='password_reset_confirm'),
               path('password_reset_complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                    name='password_reset_complete'),

               ]

women/urls.py
from django.urls import path, re_path, register_converter
from women import views
from women import converters
from django.views.decorators.cache import cache_page


register_converter(converters.FourDigitYearConverter, 'year4')


urlpatterns = [path('', views.WomenHome.as_view(), name='home'),
               path('about/', views.about, name='about'),
               path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
               path('add_page/', views.AddPage.as_view(), name='addpost'),
               path('edit/<int:pk>', views.UpdatePage.as_view(), name='editpost'),
               path('delete/<int:pk>', views.DeletePage.as_view(), name='deletepost'),
               path('contact/', views.Contact.as_view(), name='contact'),
               path('category/<slug:cat_slug>/', views.WomenCategory.as_view(), name='category'),
               path('tag/<slug:tag_slug>', views.WomenTag.as_view(), name='tag'),
               ]

women/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class PublishedModel(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Women.Status.PUBLISHED)


class Women(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = (0, 'Черновик')
        PUBLISHED = (1, 'Опубликовано')

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    content = models.TextField(blank=True, verbose_name="Текст статьи")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default=None, blank=True, null=True)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)), default=Status.DRAFT, verbose_name="Статус")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name="Категории")
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='posts', default=None, null=True)
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name="Теги")
    husband = models.OneToOneField('Husband', null=True, on_delete=models.SET_NULL, related_name='woman', verbose_name="Муж", blank=True)

    objects = models.Manager()
    published = PublishedModel()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    class Meta:
        ordering = ["-time_create"]
        indexes = [models.Index(fields=['-time_create']), ]
        verbose_name = 'Известные женщины'
        verbose_name_plural ='Известные женщины'


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=100, unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})


class Husband(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField(null=True)
    m_count = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return self.name


class UploadFiles(models.Model):
    file = models.FileField(upload_to='photos/%Y/%m/%d')

women/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible
from captcha.fields import CaptchaField

from women.models import Category, Husband, Women


@deconstructible
class RusValidator:
    ALLOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдеёжзийклмнопрстуфхцчшщбыъэюя0123456789- "
    code = 'ru'

    def __init__(self, message=None):
        self.message = message if message else "Only rus letters"

    def __call__(self, value, *args, **kwargs):
        if not set(value) <= set(self.ALLOWED_CHARS):
            raise ValidationError(self.message, code=self.code, params={'value': value})


class AddPostForm(forms.ModelForm):
    cat = forms.ModelChoiceField(queryset=Category.objects.all(), label='Категория', empty_label='Категория не выбрана')
    husband = forms.ModelChoiceField(queryset=Husband.objects.all(), label='Муж', empty_label='Не замужем', required=False)

    class Meta:
        model = Women
        fields = ['title', 'slug', 'photo', 'content', 'is_published', 'cat', 'husband', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 70, 'rows': 5})
        }
        labels = {
            'slug': 'URL',
            'photo': 'Фото'
        }

    def clean_title(self):
        max_length = 50
        title = self.cleaned_data['title']
        if len(title) > max_length:
            raise ValidationError('Длина превышает 50 символов')

        return title


class UploadFileForm(forms.Form):
    file = forms.ImageField(label='Файл')


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))
    captcha = CaptchaField()

women/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from django.core.cache import cache

from women.forms import AddPostForm, UploadFileForm, ContactForm
from women.models import Women, Category, TagPost, UploadFiles
from women.utils import DataMixin


def handle_file_upload(f):
    with open(f"uploads/{f.name}", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)


class WomenHome(DataMixin, ListView):
    title_page = 'Главная страница'
    template_name = 'women/index.html'
    context_object_name = 'posts'
    extra_context = {'cat_selected': 0}
    #permission_required = 'women.view_women'

    def get_queryset(self):
        w_list = cache.get('posts_list')
        if not w_list:
            w_list = Women.published.all().select_related('cat')
            cache.set('posts_list', w_list, 20)
        return w_list


@login_required
def about(request):
    contact_list = Women.published.all()
    women_paginator = Paginator(contact_list, 3)

    page_num = request.GET.get('page')
    page = women_paginator.get_page(page_num)
    data = {'title': 'About site', 'page': page}
    return render(request, 'women/about.html', data)


class WomenCategory(DataMixin, ListView):

    template_name = 'women/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = context['posts'][0].cat
        return self.get_mixin_context(context, title=f"Категория - {cat.name}", cat_selected=cat.pk)

    def get_queryset(self):
        return Women.published.filter(cat__slug=self.kwargs['cat_slug']).select_related('cat')


class ShowPost(DataMixin, DetailView):
    template_name = 'women/post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        return get_object_or_404(Women.published, slug=self.kwargs[self.slug_url_kwarg])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title=context['post'].title)


class WomenTag(DataMixin, ListView):
    template_name = 'women/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = TagPost.objects.get(slug=self.kwargs['tag_slug'])
        return self.get_mixin_context(context, title=f"Тег - {tag.tag}")

    def get_queryset(self):
        return Women.published.filter(tags__slug=self.kwargs['tag_slug']).select_related('cat')


class AddPage(LoginRequiredMixin, DataMixin, CreateView):
    template_name = 'women/add_page.html'
    form_class = AddPostForm
    title_page = 'Добавить пост'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class UpdatePage(UpdateView):
    template_name = 'women/add_page.html'
    model = Women
    fields = ['title', 'content', 'photo', 'is_published', 'cat']
    success_url = reverse_lazy('home')


class DeletePage(DeleteView):
    template_name = 'women/add_page.html'
    success_url = reverse_lazy('home')
    model = Women


class Contact(LoginRequiredMixin, DataMixin, FormView):
    form_class = ContactForm
    success_url = reverse_lazy('home')
    template_name = 'women/contact.html'
    title_page = "Обратная связь"

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


def page_not_found(request, exception):
    return HttpResponseNotFound('Page not found')

women/templates/women/about.html
{% extends 'base.html' %}
{% block content %}
<p>{{ title }}</p>
{% for p in page %}
<p>{{ p.pk }} :{{ p }}
{% endfor %}

<nav>
    <ul>
        {% for n in page.paginator.page_range %}
        <li>
            <p><a href="?page={{ n }}">{{ n }}</a></p>
        </li>
        {% endfor %}
    </ul>
</nav>



{% endblock content %}

women/templates/women/add_page.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ title }}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Ok</button></p>
</form>
{% endblock %}

women/templates/women/cat_list.html
{% for cat in cats %}
{% if cat.id == cat_selected %}
<li class="selected">{{cat.name}}</li>
{% else %}
<li><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li>
{% endif %}
{% endfor %}

women/templates/women/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Отправить</button>
</form>

{% endblock %}

women/templates/women/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for post in posts %}
<li><div class="article-panel">
         <p class="first">Категория: {{post.cat.name}} | автор: {{ post.author.username|default:'неизвестен' }}</p>
         <p class="last">Дата: {{post.time_update|date:"d-m-Y H:i:s"}}</p>
</div>
	{% if post.photo %}
	<p><img class="img-article-left thumb" src="{{ post.photo.url }}" alt=""></p>
	{% endif %}
		<h2>{{post.title}}</h2>
    {% autoescape off %}
	{{post.content|truncatewords:40}}
	{% endautoescape %}
		<div class="clear"></div>
			<p class="link-read-post"><a href="{{ post.get_absolute_url }}">Read post</a></p>
	</li>
	{% endfor %}
</ul>
{% endblock %}
{% block navigation %}
{% if page_obj.has_other_pages %}
<nav class="list-pages">
	<ul>
		{% if page_obj.has_previous %}
		<li class="page-num">
			<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
		</li>
		{% endif %}
		{% for p in paginator.page_range %}
		{% if p == page_obj.number %}
		<li  class="page-num page-num-selected">{{ p }}</li>
		{% elif p >= page_obj.number|add:-2 or p >= page_obj.number|add:2 %}
		<li class="page-num"><a href="?page={{ p }}">{{ p }}</a></li>
		{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
		<li class="page-num">
			<a href="?page={{ page_obj.next_page_number }}">&gt;</a>
		</li>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endblock %}

{% block breadcrumbs %}{% endblock breadcrumbs %}

women/templates/women/post.html
{% extends 'base.html' %}
{% block breadcrumbs %}
{% with post.tags.all as tags %}
{% if tags %}
<ul class="tags-list">
    <li>Теги:</li>
    {% for tag in tags %}
    <li><a href="{{ tag.get_absolute_url }}">{{ tag.tag }}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% if perms.women.change_women %}
<p><a href="{% url 'editpost' post.pk %}">Редактировать</a></p>
{% endif %}
{% endblock breadcrumbs %}
{% block content %}
<h1>{{ title }}</h1>
<p>{{ post.content|linebreaks }}</p>
{% if post.photo %}
<p><img class="img-article-left" src="{{ post.photo.url }}" alt="photo"></p>
{% endif %}
{% endblock %}

women/templates/women/tag_list.html
{% if tags %}
<p>Теги:</p>
<ul class="tags-list">
    {% for tag in tags %}
    <li><a href="{{ tag.get_absolute_url }}">{{ tag.tag }}</a></li>
    {% endfor %}
</ul>
{% endif %}